plugins {
    id 'com.android.library'
    id 'kotlin-android'
}

android {
    compileSdk = libs.versions.compileSdkVersion.get().toInteger()

    defaultConfig {
        minSdkVersion libs.versions.minSdkVersion.get().toInteger()
        targetSdkVersion libs.versions.targetSdkVersion.get().toInteger()

        vectorDrawables {
            useSupportLibrary true
        }

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlin {
        jvmToolchain(17)
    }

    flavorDimensions 'gms'
    productFlavors {
        nongms {
            dimension 'gms'
        }
        fullgms {
            dimension 'gms'
        }
    }

    namespace 'com.thewizrd.weathericons'
}

dependencies {
    coreLibraryDesugaring libs.desugar.jdk.libs

    implementation project(":shared_resources")

    testImplementation libs.junit
    androidTestImplementation libs.test.ext.junit
    androidTestImplementation libs.espresso.core

    implementation libs.annotation
    implementation libs.core.ktx
}